---
name: Test

'on': push

jobs:
  main:
    services:
      nginx:
        image: docker://harbor.ueni.xyz/proxy/library/nginx:alpine
        ports:
          - 8080:80
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - self-hosted
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.0
      - run: mkdir .hidden-folder
      - run: touch .hidden-folder/file file
      - uses: docker://busybox:1
        with:
          entrypoint: sh
          args: -c "touch $HOME/file"
      - name: Run colpal/actions-clean@${{ github.ref }}
        uses: ./
      - run: '! test -d .hidden-folder
              && ! test -f file'
      - uses: docker://busybox:1
        with:
          entrypoint: sh
          args: -c "! test -f $HOME/file"
